TypeScript version of Contoso Product
OfficeDev/Copilot-for-M365-Samples pull request #79
Opened 2024-02-07 05:06 UTC by rabwill

2024-02-18 22:28 UTC, rabwill commented
hey @garrytrinder this is ready to be reviewed and merged. CC @BobGerman

2024-03-21 16:33 UTC, garrytrinder requested changes
Apologies for the delay on this @rabwill, 

Thanks for making the changes in from the previous comments, there are a few things that I think we need to address before we merge.

I was able to get this working fine in Teams, but when using it in Copilot, I was unable to go through the authentication flow (when I click on the `Sign in` button) it does nothing.

2024-04-04 01:24 UTC, rabwill commented on samples/msgext-product-support-sso-ts/infra/botRegistration/azurebot.bicep
@garrytrinder can you check if this updated version is what you meant by whitespace consistency? Thanks

2024-04-04 01:24 UTC, rabwill commented on samples/msgext-product-support-sso-ts/infra/azure.parameters.local.json
@garrytrinder can you check if this updated version is what you meant by whitespace consistency? Thanks

2024-04-04 01:26 UTC, rabwill commented on samples/.DS_Store
I will need some help I cannot find this in my local :( @garrytrinder is it possible to remove this while merging?

2024-04-04 01:28 UTC, rabwill commented
> Apologies for the delay on this @rabwill,
> 
> Thanks for making the changes in from the previous comments, there are a few things that I think we need to address before we merge.
> 
> I was able to get this working fine in Teams, but when using it in Copilot, I was unable to go through the authentication flow (when I click on the `Sign in` button) it does nothing.

Thanks @garrytrinder I have addressed most of the issue you have raised except testing in copilot. I need to repro this before I can fix the issue. Thanks for your patience!

2024-07-11 15:40 UTC, garrytrinder approved these changes

2024-07-11 15:40 UTC, merged